#%RAML 1.0 NamedExample
value: |
  {
    "productId": "7c9be8ad-0791-4362-b195-a53dcca4e1d7",
    "variantId": "6a3c6342-af6c-402a-9f63-55e76a0de99a",
    "quantity": 2,
    "locationId": "2d9df8be-a185-4dde-9577-d6edf6cdb398",
    "deliveryMethod": "SHIPMENT",
    "locationType": "PARTNER",
    "customerId": "google-oauth2_1234567890",
    "name": "John Doe",
    "price": "64.17",
    "address": {
      "street": "1223 Fake St.",
      "city": "San Francisco",
      "postalCode": "94108",
      "state": "CA",
      "country": "US"
    },
    "partnerId": "2d9df8be-a185-4dde-9577-d6edf6cdb398"
  }